export const REFERENCE_CODE_HELPER = 'Optional internal reference code. Can be auto-generated or left blank.';

export const PAGE_GUIDANCE = {
  dashboard: {
    title: 'Dashboard instructions',
    sections: {
      purpose: 'Use the dashboard to see what needs attention first across projects, sessions, uploads, and review work.',
      steps: [
        'Scan the summary cards to see where work is blocked or ready to move.',
        'Open the project, session, or media area that has the highest operational risk.',
        'Use the Next Step prompt to continue the workflow instead of jumping between unrelated records.',
      ],
      parts: [
        'Summary cards show the main work queues.',
        'Projects nearing publish readiness shows which jobs are almost ready for release.',
        'Recent operational activity shows the latest session movement.',
      ],
      example: 'Example: If uploads needing mapping spikes after a field day, open Media Library next and match each uploaded file to the right session before review starts.',
      after: 'After you identify the next bottleneck, move into the page named in the Next Step prompt and complete that task there.',
      tips: [
        'Do not treat dashboard counts as client-safe content.',
        'Use the dashboard to decide what to do next, not to edit every record directly from here.',
      ],
      nextStep: 'Next: Open the project or work queue that is blocking progress.',
    },
  },
  clients: { title: 'Client instructions', sections: { purpose: 'Use this page to create and maintain the client organization record that projects and portal access depend on.', steps: ['Create the client once.', 'Add the main contact details.', 'Use the record when you create projects for that client.'], parts: ['The list shows all client organizations.', 'The search box finds clients by name or code.', 'The form stores contact, status, and note details.'], example: 'Example: Create “City of Pasadena” once, then attach every Pasadena documentation project to that client record.', after: 'After the client exists, create the project that belongs to that client.', tips: ['Keep internal notes internal.', 'Only add client-visible notes if they are actually meant for the portal.'], nextStep: 'Next: Create Project.' } },
  projects: { title: 'Project instructions', sections: { purpose: 'Use this page to create the top-level project record before you break the work into segments and sessions.', steps: ['Create the project.', 'Attach it to the correct client.', 'Fill in location and scope details.', 'Save it, then open the project detail page if you need readiness tracking.'], parts: ['The project list shows all jobs.', 'Filters help you narrow by status.', 'The form stores codes, location, dates, and scope settings.'], example: 'Example: Create “Downtown ADA Corridor 2026” for a city client, then use that project to organize all corridor segments and capture work.', after: 'After the project is saved, create street segments for the corridor or project area.', tips: ['Do not wait to build a perfect project record before creating segments.', 'Keep project codes short and internal.'], nextStep: 'Next: Create Street Segments.' } },
  street_segments: { title: 'Street Segment instructions', sections: { purpose: 'Use this page to break a project into the actual streets, blocks, or grouped areas that will be documented.', steps: ['Add the segment.', 'Enter its street and boundary information.', 'Save it.', 'Generate the default capture sessions for that segment.'], parts: ['The list shows all segments.', 'Search and project filters narrow the list.', 'Each segment card shows quick actions, including generating default sessions.'], example: 'Example: Create “Elm Street — Oak Ave to Pine Ave,” then generate Right Profile, Left Profile, Curb Line / Edge of Pavement, and Cross Section sessions for that block.', after: 'After the segment exists, generate or adjust capture sessions, then plan the route.', tips: ['Sequence order controls how segments appear.', 'Use clear from/to intersections so field crews know the exact limits.'], nextStep: 'Next: Generate Capture Sessions.' } },
  capture_sessions: { title: 'Capture Session instructions', sections: { purpose: 'Use this page to manage the ordered capture sessions that each segment needs.', steps: ['Review or generate the default sessions.', 'Adjust session names, order, or status.', 'Assign dates and staff if needed.', 'Use the recommended order when planning field work and matching uploads.'], parts: ['The list shows all sessions.', 'The order controls recommended field sequence and upload matching suggestions.', 'The form stores the view type, assignment, schedule, and notes.'], example: 'Example: For one segment, keep Right Profile first, Left Profile second, Curb Line / Edge of Pavement third, and Cross Section fourth so uploads can be matched in the same order later.', after: 'After the session list is right, plan the route for each session.', tips: ['Use the status helper text to avoid moving a session forward too early.', 'Leave the session code blank if you do not need a custom internal reference.'], nextStep: 'Next: Plan Route.' } },
  route_editor: { title: 'Route Editor instructions', sections: { purpose: 'Use this page to draw or adjust the route that a capture session should follow in the field.', steps: ['Select the project, segment, and session.', 'Use the route suggestion or map tools to build the path.', 'Place checkpoints in travel order.', 'Save the route when start and end are clear.'], parts: ['The setup panel scopes the route.', 'The map lets you search, zoom, draw, drag points, and undo the last point.', 'The checkpoint panel controls order, naming, and visibility.'], example: 'Example: For a Right Profile session, start on the right edge of the street, place checkpoints at Pine Ave and CVS, and end at Cedar Ave.', after: 'After the route is saved, use Field Session during recording.', tips: ['Turn drawing off before placing checkpoints.', 'Use short checkpoint names that a field operator can recognize instantly.'], nextStep: 'Next: Field Session.' } },
  field_session: { title: 'Field Session instructions', sections: { purpose: 'Use this page in the field to log session timing and quickly pair taps to the planned checkpoint sequence.', steps: ['Choose the session.', 'Start the timer when recording actually begins.', 'Use the large buttons to log notable events.', 'Watch the Next Expected Checkpoint and override only if needed.', 'Finish when recording ends.'], parts: ['Session Selection chooses the active job.', 'Active Session shows timer and control buttons.', 'Next Expected Checkpoint shows what should be paired next.', 'Event History shows what has been logged.'], example: 'Example: If the planned sequence is Start, Pine Ave, CVS, Cedar Ave, the next tap after Start should suggest Pine Ave automatically.', after: 'After the session ends, upload the media and review any pairing gaps.', tips: ['Pause only for real interruptions.', 'If the route changes in the field, use the manual override so review does not inherit the wrong checkpoint order.'], nextStep: 'Next: Upload Media.' } },
  media_library: { title: 'Media Library instructions', sections: { purpose: 'Use this page to register uploads, connect them to sessions, and check whether the files are ready for review and publish.', steps: ['Register or upload the media.', 'Link each file to the right project, segment, and session.', 'Use the matching helper when several files belong to an ordered session set.', 'Fill in previews, thumbnails, and publish readiness fields.'], parts: ['Summary cards show missing previews, missing thumbnails, and files not ready for publish.', 'The matching helper suggests which uploaded file should go to which ordered session.', 'The media form stores storage type, links, previews, and review flags.'], example: 'Example: If four files were uploaded for one segment, the helper will suggest file 1 to Right Profile, file 2 to Left Profile, file 3 to Curb Line / Edge of Pavement, and file 4 to Cross Section.', after: 'After media is linked and prepared, move to Marker Review.', tips: ['Use native upload for normal in-house files.', 'Use external link only when the original master must stay outside the app.'], nextStep: 'Next: Marker Review.' } },
  marker_review: { title: 'Marker Review instructions', sections: { purpose: 'Use this page to review markers, fix labels or timing, and make sure only approved marker references are client visible.', steps: ['Filter to the project, session, or media you need.', 'Review each marker label, type, timing, and visibility.', 'Fix anything unclear before the project moves forward.'], parts: ['Filters narrow the marker queue.', 'The marker list shows confidence and visibility state.', 'The edit form updates timing, notes, and client visibility.'], example: 'Example: Rename a vague marker like “Corner” to “Pine Ave northeast curb ramp” so reviewers and clients understand the exact reference.', after: 'After markers are reviewed, return to the project detail page for release readiness.', tips: ['Do not expose internal-only review notes.', 'Use precise labels instead of shorthand.'], nextStep: 'Next: Return to Project Detail.' } },
  project_detail: { title: 'Project Detail instructions', sections: { purpose: 'Use this page to see whether the whole project is ready to move from planning to client release.', steps: ['Review blockers and warnings.', 'Check coverage counts for segments, sessions, media, and markers.', 'Use the client preview summary to confirm what would actually be released.'], parts: ['Summary cards show readiness and blockers.', 'Publish checklist shows what still needs work.', 'Client preview snapshot shows the safe package only.'], example: 'Example: If sessions are complete but publish-safe media is missing, stay in Media Library until previews and thumbnails are ready.', after: 'After blockers are resolved, the project can move toward release.', tips: ['Internal review complete does not automatically mean client published.', 'Use this page as the final checkpoint before release.'], nextStep: 'Next: Release or return to the blocked workflow step.' } },
  client_project_viewer: { title: 'Client Project Viewer instructions', sections: { purpose: 'Use this page to review the published client package by segment, media, and marker.', steps: ['Read the project summary.', 'Filter by segment or view type.', 'Review the published media and markers for the area you care about.'], parts: ['The summary card explains what is published.', 'Filters narrow the visible package.', 'Tabs separate segments, media, and markers.'], example: 'Example: A client reviewer can filter to one segment and only look at Cross Section media for that block.', after: 'After review, send questions or requested additions back to CCG.', tips: ['Missing content may still be unpublished.', 'This page shows the approved package, not internal QA data.'], nextStep: 'Next: Contact CCG if more coverage is needed.' } },
  asset_locations: { title: 'Asset Location instructions', sections: { purpose: 'Use this page only when you want a reusable location record for landmarks, intersections, or other persistent references.', steps: ['Open this page only if you need a reusable landmark record.', 'Create the asset directly or copy it from an existing checkpoint or marker.', 'Use the saved asset later when you want consistent references across sessions.'], parts: ['The list shows saved reusable assets.', 'Quick-create options copy data from a checkpoint or marker so you do not retype it.', 'The form stores the reusable location details.'], example: 'Example: Turn the repeated “CVS at Pine Ave” checkpoint into one Asset Location so future sessions can reference the same landmark.', after: 'After the reusable asset exists, return to route, field, or marker work as needed.', tips: ['This page is optional.', 'Do not create duplicate assets when a checkpoint or marker already has the information you need.'], nextStep: 'Next: Return to the workflow page you were working on.' } },
};
