export const REFERENCE_CODE_HELPER = 'Optional internal reference code. Use it only when your team needs a stable shorthand.';

export const PAGE_GUIDANCE = {
  dashboard: {
    title: 'Dashboard instructions',
    sections: {
      purpose: 'Use the dashboard to see which projects, sessions, entries, media pairings, and review queues need attention first in the new session-first workflow.',
      steps: ['Scan the summary cards.', 'Check which projects have active capture sessions or missing media pairing.', 'Jump directly into sessions, entries, media, or timeline review based on the current bottleneck.'],
      parts: ['Summary cards highlight workflow volume.', 'Project readiness cards show which jobs are closest to release.', 'Recent activity shows live session and upload movement.'],
      example: 'Example: If uploaded media is increasing faster than timeline indexing, open Media Library to pair files with GPX/FIT tracks before client review starts.',
      after: 'After you identify the bottleneck, move into the specific workflow page and finish that step there.',
      tips: ['Use the dashboard to decide what happens next, not as a substitute for detailed editing.', 'Internal counts and statuses are not automatically client-safe.'],
      nextStep: 'Open the page that resolves the current operational bottleneck.',
    },
  },
  clients: {
    title: 'Client instructions',
    sections: {
      purpose: 'Use this page to maintain the client record that projects and portal access rely on.',
      steps: ['Create the client once.', 'Capture the core contact information.', 'Reuse the same client record for every project belonging to that organization.'],
      parts: ['The list shows all client organizations.', 'Search finds clients quickly.', 'The form stores contact, status, and note details.'],
      example: 'Example: Create “City of Pasadena” once, then attach all Pasadena capture projects to that same client.',
      after: 'After the client exists, create a project for that client.',
      tips: ['Keep internal notes internal.', 'Only add client-visible notes when they are intended for the portal.'],
      nextStep: 'Create or update the related project.',
    },
  },
  users: {
    title: 'User instructions',
    sections: {
      purpose: 'Use this page to manage staff and client access roles for the documentation portal.',
      steps: ['Create or edit the user profile.', 'Assign the correct role.', 'Attach client users to the right organization.', 'Keep active status current.'],
      parts: ['The list shows existing user profiles.', 'Filters help you narrow by role or search text.', 'The form controls role, organization, and internal notes.'],
      example: 'Example: Add a new documenter and keep their role internal-only so they can work sessions without seeing client portal controls.',
      after: 'After profile setup, verify the user sees the correct pages for their role.',
      tips: ['Do not use ad hoc roles.', 'Never leave a client-facing user unattached to the correct client organization.'],
      nextStep: 'Verify the user can reach the intended workflow pages.',
    },
  },
  projects: {
    title: 'Project instructions',
    sections: {
      purpose: 'Use this page to create and organize the top-level project before teams start capture sessions, entries, and media pairing.',
      steps: ['Create the project.', 'Attach it to the right client.', 'Describe the scope and limits.', 'Enable the expected media modes.'],
      parts: ['The project list shows all jobs.', 'Filters narrow by status.', 'The form stores scope, dates, and portal-facing notes.'],
      example: 'Example: Create “Downtown ADA Corridor 2026” and then manage every capture session, GPS pairing, and portal release inside that project.',
      after: 'After the project is saved, create the capture sessions that will collect the work.',
      tips: ['Do not wait for perfect scope detail before creating the project.', 'Projects are the top container; sessions and entries carry the operational detail.'],
      nextStep: 'Create capture sessions for the project.',
    },
  },
  project_detail: {
    title: 'Project detail instructions',
    sections: {
      purpose: 'Use this page to track the full project from session planning through media pairing, timeline indexing, review, and client release.',
      steps: ['Review the project summary.', 'Check session, entry, media, and timeline counts.', 'Open the workflow area that still has blockers.', 'Confirm what will be visible to the client.'],
      parts: ['Summary cards show workflow progress.', 'Project facts describe scope and release state.', 'Readiness panels show whether timeline and media work are complete enough for review.'],
      example: 'Example: If a project has uploaded video but no indexed timeline items, stay internal and finish entries plus timeline indexing before publication.',
      after: 'After blockers are resolved, release the client-safe package through the portal workflow.',
      tips: ['Internal completeness and client publication are different states.', 'Do not publish until media, notes, and timeline records are clean and client-safe.'],
      nextStep: 'Resolve the remaining blocker or publish when the package is ready.',
    },
  },
  capture_sessions: {
    title: 'Capture session instructions',
    sections: {
      purpose: 'Use this page to create and manage the sessions that represent actual field capture work for a project.',
      steps: ['Create the session.', 'Set the capture method and view type.', 'Assign staff or dates if known.', 'Move the status forward as the session progresses.'],
      parts: ['The list shows all sessions.', 'Filters help you narrow by project or status.', 'The form stores the operational settings for each session.'],
      example: 'Example: Create a “Right Profile Walkthrough” session for a corridor project and move it from planning to uploaded once the field video is in the system.',
      after: 'After the session exists, create entries during or after the field day and pair the resulting media with GPS tracks.',
      tips: ['Treat sessions as the operational backbone of the app.', 'Do not recreate old route-planning steps unless they genuinely help the session.'],
      nextStep: 'Capture entries in the field and pair the media after upload.',
    },
  },
  capture_session_entries: {
    title: 'Capture session entry instructions',
    sections: {
      purpose: 'Use this page to record the individual notes, observations, and pairing moments that make a session searchable later.',
      steps: ['Choose the session.', 'Add the note, observation, issue, or GPS-pairing entry.', 'Include timing and optional coordinates.', 'Use clear timeline labels.'],
      parts: ['The list shows all entries.', 'Search helps you find timeline content quickly.', 'The form stores title, text, timing, and GPS context.'],
      example: 'Example: Add an entry named “Approaching Pine curb ramps” with a timestamp and GPS coordinates so reviewers can find that moment later.',
      after: 'After entries are saved, they can be indexed into timeline review and exposed in the searchable portal workflow.',
      tips: ['Use concrete labels instead of vague notes.', 'Entries should describe what happened in the session, not recreate the whole project plan.'],
      nextStep: 'Index the session timeline and review the result.',
    },
  },
  field_session: {
    title: 'Field session instructions',
    sections: {
      purpose: 'Use this page during capture to run the live field session, record operational events, and keep timing tied to the active session.',
      steps: ['Choose the active session.', 'Start when capture actually begins.', 'Log events, pauses, and notable observations.', 'End the session when recording stops.'],
      parts: ['Session selection scopes the field run.', 'The active session panel shows timing and controls.', 'The event history shows what has already been logged.'],
      example: 'Example: Start the session when the operator begins walking, log a pause for a blocked sidewalk, then end the run when the final clip finishes.',
      after: 'After the session ends, upload media, pair GPX/FIT data, and add any missing entries.',
      tips: ['Only start the timer when the real capture starts.', 'Keep labels short and specific so later timeline review is easier.'],
      nextStep: 'Upload and pair the session media.',
    },
  },
  media_library: {
    title: 'Media library instructions',
    sections: {
      purpose: 'Use this page to register uploads, connect them to projects and sessions, and pair video with GPX or FIT tracks.',
      steps: ['Add or review uploaded media.', 'Attach each file to the correct project and session.', 'Pair the media with a GPX or FIT track when available.', 'Confirm preview, thumbnail, and publish readiness.'],
      parts: ['Summary cards show pairing and processing status.', 'The library list shows all uploaded media.', 'The pairing panel stores track linkage and timing notes.'],
      example: 'Example: Pair a long-form field video with the matching GPX file from the same morning so timeline indexing can use both sources together.',
      after: 'After pairing is done, review timeline indexing and client-safe notes before release.',
      tips: ['Do not leave uploaded media unattached to a session.', 'Track pairing should happen before final review whenever GPS data exists.'],
      nextStep: 'Review the indexed timeline and release state.',
    },
  },
  timeline_review: {
    title: 'Timeline review instructions',
    sections: {
      purpose: 'Use this page to review the searchable timeline built from entries, media pairings, and GPS tracks.',
      steps: ['Filter to the project or search term you need.', 'Review indexed timeline items in order.', 'Confirm titles, summaries, and linked media are accurate.', 'Use this as the final internal search QA layer.'],
      parts: ['Search narrows the indexed record set.', 'Summary cards show coverage and pairing depth.', 'Timeline cards display the searchable timeline items themselves.'],
      example: 'Example: Search for “Pine” and verify that the Pine intersection moment includes the right session, video, and GPX pairing context.',
      after: 'After timeline review is clean, publish the client-safe project package.',
      tips: ['This is not the place to rebuild old checkpoint workflows.', 'Focus on whether a user can find the right moment quickly and accurately.'],
      nextStep: 'Publish or return to the session/media record that still needs cleanup.',
    },
  },
  review_cases: {
    title: 'Review case instructions',
    sections: {
      purpose: 'Use this page to track questions, issues, and follow-up requests related to delivered project content.',
      steps: ['Create or update the case.', 'Assign the right project context.', 'Respond with clear internal or client-safe notes.', 'Close the case when resolved.'],
      parts: ['The list shows open and closed cases.', 'Status badges highlight urgency.', 'The form stores issue details and follow-up notes.'],
      example: 'Example: Open a review case when a client asks for another pass on a specific session or timeline moment.',
      after: 'After the case is resolved, update the relevant project, session, or timeline content if needed.',
      tips: ['Do not mix internal reasoning into client-safe responses.', 'Always tie the case back to the right project.'],
      nextStep: 'Update the affected record or reply to the client.',
    },
  },
  client_portal_home: {
    title: 'Client portal instructions',
    sections: {
      purpose: 'Use this page to browse the published client-safe projects available in the portal.',
      steps: ['Search for the right project.', 'Open the project viewer.', 'Review the released timeline, media, and project summary.'],
      parts: ['Search narrows the published project list.', 'Project cards show the released package at a glance.', 'Only published records appear here.'],
      example: 'Example: Search for a municipality name, open the project, and review the indexed site documentation package delivered by CCG.',
      after: 'After opening a project, use the project viewer to inspect the published package in more detail.',
      tips: ['If content is missing, it may still be unpublished.', 'This portal intentionally excludes internal workflow data.'],
      nextStep: 'Open the published project viewer.',
    },
  },
  client_project_viewer: {
    title: 'Client project viewer instructions',
    sections: {
      purpose: 'Use this page to review the published project summary, searchable timeline, and released media package.',
      steps: ['Read the project summary.', 'Search or filter the published timeline and media.', 'Open the released assets you need.', 'Send follow-up questions to CCG if required.'],
      parts: ['The summary explains the project release.', 'Search helps locate relevant timeline moments.', 'Media and timeline sections show the client-safe package.'],
      example: 'Example: Search for “Elm” to find the published timeline moments and videos covering Elm Street in the delivered package.',
      after: 'After review, coordinate any additions or corrections with CCG.',
      tips: ['Published portal content is curated and may not represent every internal record.', 'Use the client-safe notes and released media as the source of truth.'],
      nextStep: 'Review the published package or contact CCG for follow-up.',
    },
  },
  system_instructions: {
    title: 'System instruction instructions',
    sections: {
      purpose: 'Use this page to manage the instruction content that appears across the application.',
      steps: ['Review existing instructions.', 'Add or edit only the guidance that is still relevant to the v2 workflow.', 'Keep instructions scoped to the right page and role.'],
      parts: ['The list shows stored system instructions.', 'Filters narrow by page or role.', 'The form stores instruction title, body, and targeting rules.'],
      example: 'Example: Add one company-admin-only reminder for timeline review instead of keeping several overlapping route-planning notes.',
      after: 'After saving, revisit the target page and confirm the instruction appears correctly.',
      tips: ['Avoid duplicate or outdated guidance.', 'Keep instruction text aligned with the session + media + timeline model.'],
      nextStep: 'Verify the instruction on the target page.',
    },
  },
};
