export const REFERENCE_CODE_HELPER = 'Optional internal reference code. Use it only when your team needs a stable shorthand.';

export const PAGE_GUIDANCE = {
  dashboard: {
    title: 'Dashboard instructions',
    sections: {
      purpose: 'Use the dashboard to see which projects, sessions, entries, media pairings, and review queues need attention first in the new session-first workflow.',
      steps: ['Scan the summary cards.', 'Check which projects have active capture sessions or missing media pairing.', 'Jump directly into sessions, entries, media, or timeline review based on the current bottleneck.'],
      parts: ['Summary cards highlight workflow volume.', 'Project readiness cards show which jobs are closest to release.', 'Recent activity shows live session and upload movement.'],
      example: 'Example: If uploaded media is increasing faster than timeline indexing, open Media Library to pair files with GPX/FIT tracks before client review starts.',
      after: 'After you identify the bottleneck, move into the specific workflow page and finish that step there.',
      tips: ['Use the dashboard to decide what happens next, not as a substitute for detailed editing.', 'Internal counts and statuses are not automatically client-safe.'],
      nextStep: 'Open the page that resolves the current operational bottleneck.',
    },
  },
  clients: {
    title: 'Client instructions',
    sections: {
      purpose: 'Use this page to maintain the client record that projects and portal access rely on.',
      steps: ['Create the client once.', 'Capture the core contact information.', 'Reuse the same client record for every project belonging to that organization.'],
      parts: ['The list shows all client organizations.', 'Search finds clients quickly.', 'The form stores contact, status, and note details.'],
      example: 'Example: Create “City of Pasadena” once, then attach all Pasadena capture projects to that same client.',
      after: 'After the client exists, create a project for that client.',
      tips: ['Keep internal notes internal.', 'Only add client-visible notes when they are intended for the portal.'],
      nextStep: 'Create or update the related project.',
    },
  },
  users: {
    title: 'User instructions',
    sections: {
      purpose: 'Use this page to manage staff and client access roles for the documentation portal.',
      steps: ['Create or edit the user profile.', 'Assign the correct role.', 'Attach client users to the right organization.', 'Keep active status current.'],
      parts: ['The list shows existing user profiles.', 'Filters help you narrow by role or search text.', 'The form controls role, organization, and internal notes.'],
      example: 'Example: Add a new documenter and keep their role internal-only so they can work sessions without seeing client portal controls.',
      after: 'After profile setup, verify the user sees the correct pages for their role.',
      tips: ['Do not use ad hoc roles.', 'Never leave a client-facing user unattached to the correct client organization.'],
      nextStep: 'Verify the user can reach the intended workflow pages.',
    },
  },
  projects: {
    title: 'Project instructions',
    sections: {
      purpose: 'Use this page to create and organize the top-level project before teams start capture sessions, entries, and media pairing.',
      steps: ['Create the project.', 'Attach it to the right client.', 'Describe the scope and limits.', 'Enable the expected media modes.'],
      parts: ['The project list shows all jobs.', 'Filters narrow by status.', 'The form stores scope, dates, and portal-facing notes.'],
      example: 'Example: Create “Downtown ADA Corridor 2026” and then manage every capture session, GPS pairing, and portal release inside that project.',
      after: 'After the project is saved, create the capture sessions that will collect the work.',
      tips: ['Do not wait for perfect scope detail before creating the project.', 'Projects are the top container; sessions and entries carry the operational detail.'],
      nextStep: 'Create capture sessions for the project.',
    },
  },
  project_detail: {
    title: 'Project detail instructions',
    sections: {
      purpose: 'Use this page to see whether a project is actually ready under the new session-first model: entries created, sessions generated, uploads paired, timeline indexed, then client release.',
      steps: ['Open the project and scan the readiness cards.', 'Check whether entries and generated sessions exist.', 'Confirm videos and GPX/FIT files are attached and paired.', 'Make sure timeline indexing is complete before publication.'],
      parts: ['Metric cards show readiness counts in the order crews work.', 'Project summary explains scope and limits.', 'The readiness checklist tells you exactly which stage is still blocking delivery.'],
      example: 'Example: If “Videos uploaded” is complete but “GPX/FIT paired” is still pending, send the team to Media Library before you move toward client publication.',
      after: 'After every readiness step is marked ready, publish the cleaned client-safe package.',
      tips: ['Treat publication as the last step, not the default.', 'If timeline indexing is incomplete, the project is not ready even if media already exists.'],
      nextStep: 'Open the page tied to the first pending readiness step.',
    },
  },
  capture_sessions: {
    title: 'Capture session instructions',
    sections: {
      purpose: 'Use this page to manage the generated session stack for each entry and see, in one place, whether each session has been recorded, uploaded, paired with GPX/FIT, and indexed into the timeline.',
      steps: ['Open the project or search for the entry you need.', 'Check session order so crews record in the intended sequence.', 'Review recording status, media upload status, GPX/FIT pairing, and timeline indexing.', 'Only create a manual session if the generated set does not cover the field need.'],
      parts: ['The session cards show the generated run order.', 'Status chips show field progress and QA state.', 'The readiness panels on each card tell you whether media, track pairing, and timeline indexing are complete.'],
      example: 'Example: A “Main Street — Left Profile” session should move from planned to uploaded once the video is in Media Library, then to synced/indexed after the matching GPX file is paired.',
      after: 'After a session is ready or active, crews use Field Session to run it and Media Library to pair its uploads.',
      tips: ['Do not rebuild the old segment-planning workflow here.', 'If the generated sessions are correct, the only remaining work is recording, pairing, and indexing.'],
      nextStep: 'Run the session in the field or finish its media pairing and indexing.',
    },
  },
  capture_session_entries: {
    title: 'Capture session entry instructions',
    sections: {
      purpose: 'Use this page to define the roadway, frontage, and range entries that drive session generation. This is the setup page crews fill out before any recording begins.',
      steps: ['Add one entry for each roadway, frontage, or range you need to capture.', 'Enter the road or range details in plain language.', 'Turn on the standard views you want included and add 360 only when needed.', 'Use Generate Sessions to create the full recording stack automatically.'],
      parts: ['The entry cards show the corridor definition and selected views.', 'The generated session list shows what the system will create or has already created.', 'The form keeps setup light by focusing on road/range details instead of manual segment building.'],
      example: 'Example: Enter “Main Street from Oak Ave to Elm Ave,” keep the standard views on, add optional 360 if needed, then generate Right Profile, Left Profile, Curb Line, and Cross Section sessions automatically.',
      after: 'After the sessions are generated, go to Capture Sessions or Field Session to run them in the field.',
      tips: ['Write entries the way crews talk about the area in the field.', 'Do not break a normal corridor into manual checkpoints unless there is a real operational reason.'],
      nextStep: 'Generate the sessions and move into field capture.',
    },
  },
  field_session: {
    title: 'Field session instructions',
    sections: {
      purpose: 'Use this page while a generated session is actually being recorded. Start the timer, keep the crew aligned on the GPS/track workflow, and log only the notes that matter later.',
      steps: ['Choose the generated session you are about to record.', 'Start the session when the camera and GPS/FIT device begin together.', 'Add short notes only for pauses, odd conditions, or markers worth finding later.', 'Complete the session when recording stops and hand it off to upload + pairing.'],
      parts: ['The active session panel shows which generated run is live.', 'The timer keeps later pairing grounded in real capture time.', 'The event note area is optional and meant for exceptions, not heavy manual checkpoint entry.'],
      example: 'Example: Start “Robert Street — Right Profile” when the camera starts rolling, add one pause note for a blocked lane, then complete the session and upload the video plus GPX file afterward.',
      after: 'After handoff, move to Media Library to upload files, pair the GPX/FIT track, and start indexing.',
      tips: ['If nothing unusual happens, you may only need start and stop.', 'Short, specific notes help sync review far more than long narrative logs.'],
      nextStep: 'Upload the video and GPX/FIT files for this session.',
    },
  },
  media_library: {
    title: 'Media library instructions',
    sections: {
      purpose: 'Use this page to upload session video, upload GPX/FIT files, pair them together, review sync status, and see whether indexing plus cut suggestions are ready.',
      steps: ['Upload the video and attach it to the generated session.', 'Upload the GPX/FIT file for that same session.', 'Pair the two records together and review the sync status.', 'Check indexing status and suggested cut points before moving to timeline review.'],
      parts: ['Summary cards show upload, pairing, and suggested-cut volume.', 'Each media card shows the linked session, current track pairing, sync preview, and indexing state.', 'The side controls let you pair a GPX/FIT file directly to the matching session video.'],
      example: 'Example: Upload the “Main Street Right Profile” MP4, upload the Garmin GPX file from the same run, pair them on the same media card, then confirm the sync preview before timeline review.',
      after: 'After media and track pairing are complete, open Timeline Review to confirm the generated metadata.',
      tips: ['Pair files as soon as they land so indexing has the best input.', 'If a video is not attached to a session, it will be much harder to search and review later.'],
      nextStep: 'Confirm the generated timeline metadata.',
    },
  },
  timeline_review: {
    title: 'Timeline review instructions',
    sections: {
      purpose: 'Use this page to review the automatically generated timeline/location metadata produced from session video plus GPX/FIT pairing.',
      steps: ['Filter to the project you are cleaning up.', 'Review the likely intersections, address references, nearby places, timestamps, and search text.', 'Confirm good matches, edit weak ones, and reject bad matches.', 'Use suggested cut points to spot major moments worth preserving.'],
      parts: ['The summary cards show metadata coverage and cut-point volume.', 'Each timeline card shows the likely location labels, timestamp, search text, and linked media.', 'The action buttons let you confirm, edit, or reject a generated row quickly.'],
      example: 'Example: If the system suggests “Main St & Elm Ave” at 03:24 and the video really shows that intersection, confirm it; if it should be “Main St & Park Ave,” edit it before release.',
      after: 'After the metadata is confirmed, the project is much closer to client publication.',
      tips: ['Focus on findability first: can someone search and reach the right moment?', 'Reject bad location guesses instead of leaving them ambiguous.'],
      nextStep: 'Finish metadata QA or publish the cleaned project package.',
    },
  },
  review_cases: {
    title: 'Review case instructions',
    sections: {
      purpose: 'Use this page to track questions, issues, and follow-up requests related to delivered project content.',
      steps: ['Create or update the case.', 'Assign the right project context.', 'Respond with clear internal or client-safe notes.', 'Close the case when resolved.'],
      parts: ['The list shows open and closed cases.', 'Status badges highlight urgency.', 'The form stores issue details and follow-up notes.'],
      example: 'Example: Open a review case when a client asks for another pass on a specific session or timeline moment.',
      after: 'After the case is resolved, update the relevant project, session, or timeline content if needed.',
      tips: ['Do not mix internal reasoning into client-safe responses.', 'Always tie the case back to the right project.'],
      nextStep: 'Update the affected record or reply to the client.',
    },
  },
  client_portal_home: {
    title: 'Client portal instructions',
    sections: {
      purpose: 'Use this page to browse the published client-safe projects available in the portal.',
      steps: ['Search for the right project.', 'Open the project viewer.', 'Review the released timeline, media, and project summary.'],
      parts: ['Search narrows the published project list.', 'Project cards show the released package at a glance.', 'Only published records appear here.'],
      example: 'Example: Search for a municipality name, open the project, and review the indexed site documentation package delivered by CCG.',
      after: 'After opening a project, use the project viewer to inspect the published package in more detail.',
      tips: ['If content is missing, it may still be unpublished.', 'This portal intentionally excludes internal workflow data.'],
      nextStep: 'Open the published project viewer.',
    },
  },
  client_project_viewer: {
    title: 'Client project viewer instructions',
    sections: {
      purpose: 'Use this page to review the published project summary, searchable timeline, and released media package.',
      steps: ['Read the project summary.', 'Search or filter the published timeline and media.', 'Open the released assets you need.', 'Send follow-up questions to CCG if required.'],
      parts: ['The summary explains the project release.', 'Search helps locate relevant timeline moments.', 'Media and timeline sections show the client-safe package.'],
      example: 'Example: Search for “Elm” to find the published timeline moments and videos covering Elm Street in the delivered package.',
      after: 'After review, coordinate any additions or corrections with CCG.',
      tips: ['Published portal content is curated and may not represent every internal record.', 'Use the client-safe notes and released media as the source of truth.'],
      nextStep: 'Review the published package or contact CCG for follow-up.',
    },
  },
  system_instructions: {
    title: 'System instruction instructions',
    sections: {
      purpose: 'Use this page to manage the instruction content that appears across the application.',
      steps: ['Review existing instructions.', 'Add or edit only the guidance that is still relevant to the v2 workflow.', 'Keep instructions scoped to the right page and role.'],
      parts: ['The list shows stored system instructions.', 'Filters narrow by page or role.', 'The form stores instruction title, body, and targeting rules.'],
      example: 'Example: Add one company-admin-only reminder for timeline review instead of keeping several overlapping route-planning notes.',
      after: 'After saving, revisit the target page and confirm the instruction appears correctly.',
      tips: ['Avoid duplicate or outdated guidance.', 'Keep instruction text aligned with the session + media + timeline model.'],
      nextStep: 'Verify the instruction on the target page.',
    },
  },
};
